spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    initialize: true
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true  
  h2:
    console:
      enabled: true
      settings:
        web-admin-password: sa
        
  thymeleaf:
    cache: false
    prefix: "classpath:/templates/app/"
    suffix: ".html"
